
on:
  push:
    branches: [ develop ]

jobs:
  cool-weather:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
          python-version: '3.8'
    - name: Build client
      run: |
        echo "*** Building client"
        server_pwd=$PWD
        cd omdbweather/frontend/cool-ui
        npm install
        mkdir $server_pwd/omdbweather/client_files
        npm run build -- --output-path $server_pwd/omdbweather/client_files
        cd -
    - name: Build server
      run: |
        echo "*** Building Server"
        pip install virtualenv
        python setup.py clean --all

        virtualenv venv
        source venv/bin/activate

        pip install -r requirements.txt
        ls -l omdbweather/client_files
    - name: Build Docker
      run: |
        TAG=1.0.0
        REPO=omdbweather
        IMAGE=omdbweather

        docker build  -t $REPO/$IMAGE:$TAG -f Dockerfile .
        docker image ls

    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: omdbweather
        password: omdbweather
        repository: omdbweather/omdbweather:1.0.1
        tag_with_ref: true
  